{% set name = "nakametpy" %}
{% set version = "2024.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f3942909cbb49b9a70e030f96a7ee4a6b3ff3155d17e7d1aa15195c9b6c24bb0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - matplotlib >=3.3.0
    - nose >=1.3.0
    - numpy <=1.21.1   # [ py < 311 ]
    - numpy >=1.21.2   # [ py >= 311 ]
    - pip
    - python
  run:
    - matplotlib >=3.3.0
    - nose >=1.3.0
    - numpy <=1.21.1   # [ py < 311 ]
    - numpy >=1.21.2   # [ py >= 311 ]
    - python

test:
  imports:
    - nakametpy

about:
  home: "https://github.com/muchojp/NakaMetPy"
  license: BSD 3-clause
  license_family: BSD
  license_file: 
  summary: "Meteorological modules for calculation and colormap."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
